---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/mesos-dns"
    state: "directory"
    recurse: yes

- name: Copying config.json
  template:
    src: "mesos-dns.json.j2"
    dest: "{{ node_config_directory }}/mesos-dns/config.json"

- name: Copying Mesos DNS configuration files
  template:
    src: "mesos-dns.conf.j2"
    dest: "{{ node_config_directory }}/mesos-dns/mesos-dns.conf"
