---
- name: Starting ZooKeeper container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ zookeeper_image_full }}"
    name: "zookeeper"
    volumes:
      - "{{ node_config_directory }}/zookeeper/:{{ container_config_directory }}/:ro"
      - "zookeeper_data:/var/lib/zookeeper"
