---
- name: Starting ZooKeeper container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ zookeeper_image_full }}"
    name: "zookeeper"
    volumes:
      - /var/zookeeper:/var/zookeeper
