---
project_name: "keystone"

####################
# Database
####################
keystone_database_name: "keystone"
keystone_database_user: "keystone"
keystone_database_address: "{{ database_address }}"


####################
# Docker
####################
keystone_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-keystone"
keystone_tag: "{{ openstack_release }}"
# keystone_image_full: "{{ keystone_image }}:{{ keystone_tag }}"


####################
# Openstack
####################
keystone_admin_endpoint: "http://{{ keystone_auth_host }}:{{ keystone_admin_port }}/v3"
keystone_internal_endpoint: "http://{{ keystone_auth_host }}:{{ keystone_public_port }}/v3"
keystone_public_endpoint: "http://{{ keystone_auth_host }}:{{ keystone_public_port }}/v3"

keystone_logging_verbose: "{{ openstack_logging_verbose }}"
keystone_logging_debug: "{{ openstack_logging_debug }}"

openstack_keystone_auth: "{'auth_url':'{{ openstack_auth.auth_url }}','username':'{{ openstack_auth.username }}','password':'{{ openstack_auth.password }}','project_name':'{{ openstack_auth.project_name }}'}"


####################
# Resources
####################
# keystone-api
keystone_api_mem: "{{ keystone_api_mem|default('128') }}"
keystone_api_cpus: "{{ keystone_api_cpus|default('0.3') }}"
# keystone-init
keystone_init_mem: "{{ keystone_init_mem|default('512') }}"
keystone_init_cpus: "{{ keystone_init_cpus|default('0.3') }}"
