---
- name: Starting Chronos container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      CHRONOS_HTTP_PORT: "4400"
      CHRONOS_MASTER: "zk://{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }}{% if not forloop.last %},{% endif %}{% endfor %}:2181/mesos"
      CHRONOS_ZK_HOSTS: "zk://{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }}{% if not forloop.last %},{% endif %}{% endfor %}:2181"
    image: "{{ chronos_image_full }}"
    name: "chronos"
