---
project_name: "mariadb"

####################
# Database
####################
database_cluster_name: "openstack"


####################
# Docker
####################
mariadb_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mariadb"
mariadb_tag: "{{ openstack_release }}"
# mariadb_image_full: "{{ mariadb_image }}:{{ mariadb_tag }}"

#mariadb_data_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-data"
#mariadb_data_tag: "{{ openstack_release }}"
#mariadb_data_image_full: "{{ mariadb_data_image }}:{{ mariadb_data_tag }}"


####################
# Resources
####################
mariadb_mem: "{{ mariadb_mem|default('128') }}"
mariadb_cpus: "{{ mariadb_cpus|default('0.3') }}"
